server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://ep-holy-tree-am3b33xt.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_nvXY0bUIBu6q
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.application.name=expense-tracker

jwt.secret=ExpenseTrackerSecretKey2024SuperSecureKeyForJWTTokenGeneration
jwt.expiration=86400000